In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('ipo_data.csv')

In [3]:
df

,Date,IPO Name,Profile,Issue Size (in crores),QIB,HNI,RII,Total,Issue,Listing Open,Listing Close,Listing Gains(%),CMP,Current Gains (%)
0,29-07-21,Tatva Chintan,https://www.moneycontrol.com/ipo/tatva-chintan...,500.00,2.55,9.78,13.36,9.50,1083.0,2111.80,2310.25,113.32,"2,268.50",109.46
1,23-07-21,Zomato,https://www.moneycontrol.com/ipo/zomato_Z01.html,9375.00,51.79,32.96,7.45,38.25,76.0,115.00,125.85,65.59,133.35,75.46
2,19-07-21,Clean Science,https://www.moneycontrol.com/ipo/clean-science...,1546.00,156.37,206.43,9.00,93.41,900.0,1784.40,1585.20,76.13,"1,682.80",86.98
3,19-07-21,G R Infra,https://www.moneycontrol.com/ipo/g-r-infra_I13...,963.28,93.18,73.01,4.89,43.48,837.0,1700.00,1746.80,108.70,"1,730.85",106.79
4,07-07-21,India Pesticide,https://www.moneycontrol.com/ipo/india-pestici...,800.00,2.64,1.36,4.40,3.25,296.0,360.00,335.45,13.33,337.40,13.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,19-02-10,Thangamayil,https://www.moneycontrol.com/ipo/thangamayil_T...,0.00,0.52,1.52,2.26,1.12,75.0,70.00,71.10,-5.20,870.00,1060.00
260,15-02-10,Vascon Engineer,https://www.moneycontrol.com/ipo/vascon-engine...,199.80,1.12,3.65,0.62,1.22,165.0,155.90,146.38,-11.28,21.70,-86.85
261,15-02-10,Syncom Health,https://www.moneycontrol.com/ipo/syncom-health...,56.25,0.99,16.60,6.25,5.17,75.0,88.00,87.85,17.13,4.06,-94.59
262,08-02-10,Jubilant Food,https://www.moneycontrol.com/ipo/jubilant-food...,328.70,59.39,51.95,3.79,31.11,145.0,160.00,114.50,-21.03,"3,770.20",2500.14
263,03-02-10,Infinite Comp,https://www.moneycontrol.com/ipo/infinite-comp...,189.80,48.44,106.02,11.08,43.22,165.0,178.35,184.51,11.82,473.75,187.12

In [4]:
df.shape

(264, 14)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264 entries, 0 to 263
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Date                    264 non-null    object
 1   IPO Name                264 non-null    object
 2   Profile                 264 non-null    object
 3   Issue Size (in crores)  264 non-null    float64
 4   QIB                     264 non-null    float64
 5   HNI                     264 non-null    float64
 6   RII                     264 non-null    float64
 7   Total                   264 non-null    float64
 8   Issue                   264 non-null    float64
 9   Listing Open            264 non-null    float64
 10  Listing Close           264 non-null    float64
 11  Listing Gains(%)        264 non-null    float64
 12  CMP                     264 non-null    object
 13  Current  Gains (%)      262 non-null    float64
dtypes: float64(10), object(4)
memory usage: 29.0+ KB

In [7]:
df.drop(['CMP','Current  Gains (%)'],axis=1,inplace=True)

In [8]:
df.shape

(264, 12)

In [9]:
df.describe()

,Issue Size (in crores),QIB,HNI,RII,Total,Issue,Listing Open,Listing Close,Listing Gains(%)
count,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000
mean,978.718106,23.732841,68.798561,7.388371,25.944886,339.291667,403.329735,363.170152,4.290871
std,1884.758112,36.880595,136.513479,11.837761,45.444680,333.874356,437.396998,417.120358,46.343783
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.500000,1.570000,-97.150000
25%,144.250000,1.130000,1.210000,1.297500,1.570000,109.500000,117.750000,93.025000,-11.755000
50%,441.225000,4.670000,5.075000,3.380000,4.845000,220.000000,251.300000,208.225000,1.355000
75%,903.187500,32.505000,65.112500,8.392500,33.412500,447.000000,546.250000,520.425000,25.635000
max,15475.000000,176.850000,958.070000,77.930000,277.280000,1766.000000,2725.000000,3118.650000,153.500000

In [10]:
df.columns

Index(['Date', 'IPO Name', 'Profile', 'Issue Size (in crores)', 'QIB', 'HNI',
       'RII', 'Total', 'Issue', 'Listing Open', 'Listing Close',
       'Listing Gains(%)'],
      dtype='object')

In [14]:
df['Date'] = pd.to_datetime(df['Date'])

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264 entries, 0 to 263
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Date                    264 non-null    datetime64[ns]
 1   IPO Name                264 non-null    object
 2   Profile                 264 non-null    object
 3   Issue Size (in crores)  264 non-null    float64
 4   QIB                     264 non-null    float64
 5   HNI                     264 non-null    float64
 6   RII                     264 non-null    float64
 7   Total                   264 non-null    float64
 8   Issue                   264 non-null    float64
 9   Listing Open            264 non-null    float64
 10  Listing Close           264 non-null    float64
 11  Listing Gains(%)        264 non-null    float64
dtypes: datetime64[ns](1), float64(9), object(2)
memory usage: 24.9+ KB

In [16]:
df.to_excel("ipo_cleaned.xlsx", index=False)